-- Flyway migration: create all tables

-- Create master data tables first
CREATE TABLE jabatan (
  kd_jabatan INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_jabatan VARCHAR(255) NOT NULL
);

CREATE TABLE departemen (
  kd_departemen INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_departemen VARCHAR(255) NOT NULL
);

CREATE TABLE unit_kerja (
  kd_unit_kerja INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_unit_kerja VARCHAR(255) NOT NULL
);

CREATE TABLE pendidikan (
  kd_pendidikan INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_pendidikan VARCHAR(255) NOT NULL
);

CREATE TABLE jenis_kelamin (
  kd_jenis_kelamin INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_jenis_kelamin VARCHAR(50) NOT NULL
);

CREATE TABLE status_absen (
  kd_status INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_status VARCHAR(255) NOT NULL
);

-- Create pegawai table
CREATE TABLE pegawai (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_user VARCHAR(100) UNIQUE,
  profile VARCHAR(50),
  nama_lengkap VARCHAR(255),
  tempat_lahir VARCHAR(255),
  tanggal_lahir BIGINT,
  email VARCHAR(255) UNIQUE,
  password_hash VARCHAR(255),
  nik_user VARCHAR(100),
  kd_jabatan INTEGER,
  kd_departemen INTEGER,
  kd_unit_kerja INTEGER,
  kd_jenis_kelamin INTEGER,
  kd_pendidikan INTEGER,
  photo VARCHAR(512),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (kd_jabatan) REFERENCES jabatan(kd_jabatan),
  FOREIGN KEY (kd_departemen) REFERENCES departemen(kd_departemen),
  FOREIGN KEY (kd_unit_kerja) REFERENCES unit_kerja(kd_unit_kerja),
  FOREIGN KEY (kd_jenis_kelamin) REFERENCES jenis_kelamin(kd_jenis_kelamin),
  FOREIGN KEY (kd_pendidikan) REFERENCES pendidikan(kd_pendidikan)
);

-- Create presensi table
CREATE TABLE presensi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_user BIGINT,
  tgl_absensi DATE,
  jam_masuk TIME,
  jam_keluar TIME,
  kd_status INTEGER,
  nama_status VARCHAR(255),
  FOREIGN KEY (id_user) REFERENCES pegawai(id),
  FOREIGN KEY (kd_status) REFERENCES status_absen(kd_status)
);